### ISSUE TITLE
iam getting this in raspberry pi 4 running ubuntu 18.04

### ISSUE THREAD

**Issue by Suryah07** [LOGIQOS/vesta#2]
ubuntu@ubuntu:~$ curl https://vesta-arm.s3.nl-ams.scw.cloud/vst-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   225    0   225    0     0    424      0 --:--:-- --:--:-- --:--:--   424
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<?xml version='1.0' encoding='UTF-8'?>'

**Comment by jcperez2405** [comment]
The error you are getting is due repository is down:
`<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message><RequestId>txfad0b85975974735a0692-0060cb996e</RequestId><BucketName>vesta-arm</BucketName></Error>`

**Comment by Suryah07** [comment]
Then when can i install ir
